### ISSUE TITLE
generate.sh does not work on OpenBSD

### ISSUE THREAD

**Issue by ghost** [kbertalan/idris2-apache-mime-types#1]
Hello, I'm trying to use this library and the generate.sh is not working correctly. Here is the error log:
```
octeep ~/workspace/idris2-apache-mime-types: ./generate.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 60852  100 60852    0     0   101k      0 --:--:-- --:--:-- --:--:--  101k
sed: 8: "/^N: / {
  y/-/_/
  s/+ ...: more than one number or 'g' in substitute flags
octeep ~/workspace/idris2-apache-mime-types: nvim src/Data/Mime/Apache/Raw.idr
octeep ~/workspace/idris2-apache-mime-types: ./generate.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 60852  100 60852    0     0    98k      0 --:--:-- --:--:-- --:--:--   98k
sed: 8: "/^N: / {
  y/-/_/
  s/+ ...: more than one number or 'g' in substitute flags
```
Also, the path of sh is platform dependent, which may causes it to break on other distros / system.

Would you consider using Idris to write the pre-processor instead? I'd be happy to make a PR if you approve it.

**Comment by kbertalan** [comment]
Hi @octeep ,
Unfortunately, I don't own an OpenBSD system, so I cannot fix the generator to work on OpenBSD and linux too.
If you have the idea how to port the generator to idris and get rid of (the obviously hacky) sed scripts, then I am happy to accept your PR.

When I created this project I also considered idris, but I failed to find good http client library, so I fell back to the command line tools.
The best would be to use IO in elaboration, however that is not possible yet.

**Comment by ghost** [comment]
I was considering rather than using Idris to fetch the apache mime file, a shell script would be used to fetch it, then pass it to a parser written in Idris.

That said, fetching it in idris would also be doable. I am currently working on a HTTP client so that can also work. 

Edit: I've given it some thought. Using idris to fetch the file may not require a http library after all, since you can just hard code the http request and send it rawly over tcp.

Second edit: I've messed around with elab for a bit and I don't think it is feasible for such a huge gigantic file. The compilation time is unreasonably long. I think the optimal way would be to use a script to fetch the mime.types, then call a preprocessor program written in idris to generate the source code.
